FROM oven/bun:1.1.22-alpine AS base

WORKDIR /app

ARG DATABASE_URL

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json .turbo.json

COPY ./apps/backend ./apps/backend


# COPY . .

RUN bun install
RUN bun run db:generate

EXPOSE 8080

CMD [ "bun","run","start:backend" ]
