FROM oven/bun:1.1.22-alpine AS base

WORKDIR /app

ARG DATABASE_URL

COPY . .

RUN bun install
RUN DATABASE_URL=${DATABASE_URL} bun run db:generate
RUN bun run build

EXPOSE 8080

CMD [ "bun","run","start:web" ]